project:
  type: website

website:
  title: "Jason Tsukahara"
#  site-url: https://silviacanelon.com
#  favicon: assets/silvia/img/logo_rounded.svg
  page-navigation: true
  back-to-top-navigation: true
  twitter-card: true
  search: false
  
  navbar:
#    logo: assets/silvia/img/logo_rounded.svg
    pinned: true
    right:
      - href: about.qmd
        text: About Me
      - href: research/index.qmd
        text: Research
      - href: publications/index.qmd
        text: Publications
      - href: rpackages.qmd
        text: R Packages
      - href: teaching/index.qmd
        text: Teaching
      - href: assets/jtsukahara_cv.pdf
        text: CV
  
  # page-footer:  
  #   left: >-
  #    &#169; 2023 Silvia Canelón &#8729; Made with [Quarto](https://quarto.org)
  #   center: |
  #     <a class="link-dark me-1" href="/accessibility.html" title="Accessibility commitment" target="_blank" rel="noopener">{{< fa universal-access >}}</a>
  #     <a class="link-dark me-1" href="https://hachyderm.io/@spcanelon" title="mastodon" target="_blank" rel="noopener">{{< fa brands mastodon >}}</a>
  #     <a class="link-dark me-1" href="https://github.com/spcanelon" title="github" target="_blank" rel="noopener">{{< fa brands github >}}</a>
  #     <a class="link-dark me-1" href="https://orcid.org/0000-0003-1709-1394" title="orcid" target="_blank" rel="noopener">{{< ai orcid >}}</a>
  #     <a class="link-dark me-1" href="https://scholar.google.com/citations?user=GAzkvpcAAAAJ&hl=en&oi=ao" title="Google Scholar" target="_blank"rel="noopener">{{< ai google-scholar >}}</a>
  #     <a class="link-dark me-1" href="https://linkedin.com/in/spcanelon" title="LinkedIn" target="_blank" rel="noopener">{{< fa brands linkedin >}}</a>
  # 
  #   right: 
  #     - text: "Accessibility"
  #       aria-label: "Accessibility Commitment"
  #       href: accessibility.qmd
  #     - text: "Contact"
  #       aria-label: "Contact Form"
  #       href: "contact.qmd"
  #     - text: "License"
  #       aria-label: "License Details"
  #       href: license.qmd
  #     - icon: rss
  #       href: blog/index.xml
        
format:
  html:
    theme: 
      light:
        - cosmo
        - assets/custom-theme.scss
        - assets/publications.css
    code-link: true
    # pagetitle: "{{< meta title >}} | Silvia Canelón"
    lightbox: true
    toc: false

academicons:
  enabled: true

editor: visual

