---
title: "Sustaining the focus of attention and how it relates to performance in complex cognitive tasks"

author:
- name: Jason S. Tsukahara
- name: Randall W. Engle

year: "2023"
date: "2023-05-03"
publication: "PsyArxiv"
doi: "10.31234/osf.io/wd5kz"

pub-type: "Preprint"
icon-type: file-richtext
color: BC3C29FF
project:
  - ac-cogability
home-page: "yes"

links:
- icon: file-pdf
  name: PDF
  url: https://psyarxiv.com/wd5kz/
- icon: code-square
  name: Code
  url: https://osf.io/2vqas/
- icon: database
  name: Data
  url: https://osf.io/2vqas/
  
categories:
  - Sustained Attention
  - Empirical Study

summary: We show that the ability to sustain the focus of attention over a relatively short period of time is related to the ability to control attention, more generally, but not to other cognitive abilities like working memory capacity.
---

## Abstract

The ability to sustain attention over time and the maintenance of information in working memory are highly overlapping constructs. Many tasks used to measure sustained attention rely heavily on the maintenance of information in working memory to sustain continuous task performance over large periods of time. To further understand the relationship between sustained attention and working memory, we tested whether the ability to sustain the focus of attention over a relatively short period of time (e.g., 12 seconds) is related to cognitive abilities such as working memory capacity and attention control. We used a novel paradigm, the sustained attention-to-cue task, to manipulate the duration attention had tobe sustained at a cued location; none (0 seconds), short (2–5 seconds), medium (5.5–8.5 seconds), and long (9–12 seconds). We found that attention waned and accuracy decreased as the wait time got longer. Those higher on attention control ability, had less of a decline in accuracy as the wait time got longer. However, the decline in accuracy as wait time got longer was not related to working memory capacity, fluid intelligence, or multitasking. These findings challenge how we think about sustained attention and working memory capacity, and the nature of attention control more generally.
