---
title: "The relationship between baseline pupil size and intelligence"

author:
- name: Jason S. Tsukahara
- name: Tyler L. Harrison
- name: Randall W. Engle

year: "2016"
date: "2016-10-12"
publication: "Cognitive Psychology"
doi: "10.1016/j.cogpsych.2016.10.001"

pub-type: "Article"
icon-type: file-richtext
project:
  - ac-brain
  
links:
- icon: file-pdf-fill
  name: PDF
  url: /publications/2016-cp-baseline-pupil-og/2016-cp-baseline-pupil-og.pdf
  
categories:
  - Pupillometry
  - Locus Coeruleus
  - Empirical Study

summary: Across three studies we consistently found that baseline pupil size was related to cognitive ability. In order to provide an explanation and suggestions for future research, we also consider our findings in the context of the underlying neural mechanisms involved.
---

## Abstract

Pupil dilations of the eye are known to correspond to central cognitive processes. However, the relationship between pupil size and individual differences in cognitive ability is not as well studied. A peculiar finding that has cropped up in this research is that those high on cognitive ability have a larger pupil size, even during a passive baseline condition. Yet these findings were incidental and lacked a clear explanation. Therefore, in the present series of studies we systematically investigated whether pupil size during a passive baseline is associated with individual differences in working memory capacity and fluid intelligence. Across three studies we consistently found that baseline pupil size is, in fact, related to cognitive ability. We showed that this relationship could not be explained by differences in mental effort, and that the effect of working memory capacity and fluid intelligence on pupil size persisted even after 23 sessions and taking into account the effect of novelty or familiarity with the environment. We also accounted for potential confounding variables such as; age, ethnicity, and drug substances. Lastly, we found that it is fluid intelligence, more so than working memory capacity, which is related to baseline pupil size. In order to provide an explanation and suggestions for future research, we also consider our findings in the context of the underlying neural mechanisms involved.
